In [1]:
from click import group
%pip install seaborn

Collecting seaborn
  Downloading seaborn-0.13.2-py3-none-any.whl.metadata (5.4 kB)
Requirement already satisfied: numpy!=1.24.0,>=1.20 in /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages (from seaborn) (2.1.2)
Requirement already satisfied: pandas>=1.2 in /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages (from seaborn) (2.2.3)
Collecting matplotlib!=3.6.1,>=3.4 (from seaborn)
  Downloading matplotlib-3.10.0-cp313-cp313-macosx_10_13_x86_64.whl.metadata (11 kB)
Collecting contourpy>=1.0.1 (from matplotlib!=3.6.1,>=3.4->seaborn)
  Downloading contourpy-1.3.1-cp313-cp313-macosx_10_13_x86_64.whl.metadata (5.4 kB)
Collecting cycler>=0.10 (from matplotlib!=3.6.1,>=3.4->seaborn)
  Downloading cycler-0.12.1-py3-none-any.whl.metadata (3.8 kB)
Collecting fonttools>=4.22.0 (from matplotlib!=3.6.1,>=3.4->seaborn)
  Downloading fonttools-4.55.3-cp313-cp313-macosx_10_13_x86_64.whl.metadata (165 kB)
Collecting kiwisolver>=1.3.1 (from matplotlib!=3.6.1,>=3.4->seaborn)
  Downloading kiwisolver-1.4.7-cp313-cp313-macosx_10_13_x86_64.whl.metadata (6.3 kB)
Requirement already satisfied: packaging>=20.0 in /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (24.1)
Collecting pillow>=8 (from matplotlib!=3.6.1,>=3.4->seaborn)
  Downloading pillow-11.0.0-cp313-cp313-macosx_10_13_x86_64.whl.metadata (9.1 kB)
Collecting pyparsing>=2.3.1 (from matplotlib!=3.6.1,>=3.4->seaborn)
  Downloading pyparsing-3.2.0-py3-none-any.whl.metadata (5.0 kB)
Requirement already satisfied: python-dateutil>=2.7 in /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages (from pandas>=1.2->seaborn) (2024.2)
Requirement already satisfied: tzdata>=2022.7 in /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages (from pandas>=1.2->seaborn) (2024.2)
Requirement already satisfied: six>=1.5 in /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages (from python-dateutil>=2.7->matplotlib!=3.6.1,>=3.4->seaborn) (1.16.0)
Downloading seaborn-0.13.2-py3-none-any.whl (294 kB)
Downloading matplotlib-3.10.0-cp313-cp313-macosx_10_13_x86_64.whl (8.2 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 8.2/8.2 MB 16.5 MB/s eta 0:00:00a 0:00:01
Downloading contourpy-1.3.1-cp313-cp313-macosx_10_13_x86_64.whl (271 kB)
Downloading cycler-0.12.1-py3-none-any.whl (8.3 kB)
Downloading fonttools-4.55.3-cp313-cp313-macosx_10_13_x86_64.whl (2.3 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.3/2.3 MB 23.4 MB/s eta 0:00:00
Downloading kiwisolver-1.4.7-cp313-cp313-macosx_10_13_x86_64.whl (65 kB)
Downloading pillow-11.0.0-cp313-cp313-macosx_10_13_x86_64.whl (3.1 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.1/3.1 MB 26.7 MB/s eta 0:00:00
Downloading pyparsing-3.2.0-py3-none-any.whl (106 kB)
Installing collected packages: pyparsing, pillow, kiwisolver, fonttools, cycler, contourpy, matplotlib, seaborn
  WARNING: The scripts fonttools, pyftmerge, pyftsubset and ttx are installed in '/Library/Frameworks/Python.framework/Versions/3.13/bin' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
Successfully installed contourpy-1.3.1 cycler-0.12.1 fonttools-4.55.3 kiwisolver-1.4.7 matplotlib-3.10.0 pillow-11.0.0 pyparsing-3.2.0 seaborn-0.13.2
Note: you may need to restart the kernel to use updated packages.

In [11]:
import seaborn as sns
iris = sns.load_dataset('iris')
iris

     sepal_length  sepal_width  petal_length  petal_width    species
0             5.1          3.5           1.4          0.2     setosa
1             4.9          3.0           1.4          0.2     setosa
2             4.7          3.2           1.3          0.2     setosa
3             4.6          3.1           1.5          0.2     setosa
4             5.0          3.6           1.4          0.2     setosa
..            ...          ...           ...          ...        ...
145           6.7          3.0           5.2          2.3  virginica
146           6.3          2.5           5.0          1.9  virginica
147           6.5          3.0           5.2          2.0  virginica
148           6.2          3.4           5.4          2.3  virginica
149           5.9          3.0           5.1          1.8  virginica

[150 rows x 5 columns]

In [12]:
# 결측치가 있는 행을 모두 제거하세요.
iris.dropna(inplace=True)
iris

     sepal_length  sepal_width  petal_length  petal_width    species
0             5.1          3.5           1.4          0.2     setosa
1             4.9          3.0           1.4          0.2     setosa
2             4.7          3.2           1.3          0.2     setosa
3             4.6          3.1           1.5          0.2     setosa
4             5.0          3.6           1.4          0.2     setosa
..            ...          ...           ...          ...        ...
145           6.7          3.0           5.2          2.3  virginica
146           6.3          2.5           5.0          1.9  virginica
147           6.5          3.0           5.2          2.0  virginica
148           6.2          3.4           5.4          2.3  virginica
149           5.9          3.0           5.1          1.8  virginica

[150 rows x 5 columns]

In [13]:
# 중복된 행을 제거하세요.
iris.drop_duplicates(inplace=True)
iris

     sepal_length  sepal_width  petal_length  petal_width    species
0             5.1          3.5           1.4          0.2     setosa
1             4.9          3.0           1.4          0.2     setosa
2             4.7          3.2           1.3          0.2     setosa
3             4.6          3.1           1.5          0.2     setosa
4             5.0          3.6           1.4          0.2     setosa
..            ...          ...           ...          ...        ...
145           6.7          3.0           5.2          2.3  virginica
146           6.3          2.5           5.0          1.9  virginica
147           6.5          3.0           5.2          2.0  virginica
148           6.2          3.4           5.4          2.3  virginica
149           5.9          3.0           5.1          1.8  virginica

[149 rows x 5 columns]

In [16]:
# 'petal_length'가 보다 큰 행만 선택하세요.
filtered_iris = iris[iris['petal_length'] > 5]
filtered_iris.sort_values(by='petal_length', ascending=True)

     sepal_length  sepal_width  petal_length  petal_width     species
83            6.0          2.7           5.1          1.6  versicolor
101           5.8          2.7           5.1          1.9   virginica
114           5.8          2.8           5.1          2.4   virginica
110           6.5          3.2           5.1          2.0   virginica
133           6.3          2.8           5.1          1.5   virginica
141           6.9          3.1           5.1          2.3   virginica
149           5.9          3.0           5.1          1.8   virginica
147           6.5          3.0           5.2          2.0   virginica
145           6.7          3.0           5.2          2.3   virginica
111           6.4          2.7           5.3          1.9   virginica
115           6.4          3.2           5.3          2.3   virginica
148           6.2          3.4           5.4          2.3   virginica
139           6.9          3.1           5.4          2.1   virginica
112           6.8          3.0           5.5          2.1   virginica
137           6.4          3.1           5.5          1.8   virginica
116           6.5          3.0           5.5          1.8   virginica
134           6.1          2.6           5.6          1.4   virginica
140           6.7          3.1           5.6          2.4   virginica
103           6.3          2.9           5.6          1.8   virginica
128           6.4          2.8           5.6          2.1   virginica
136           6.3          3.4           5.6          2.4   virginica
132           6.4          2.8           5.6          2.2   virginica
120           6.9          3.2           5.7          2.3   virginica
124           6.7          3.3           5.7          2.1   virginica
144           6.7          3.3           5.7          2.5   virginica
129           7.2          3.0           5.8          1.6   virginica
104           6.5          3.0           5.8          2.2   virginica
108           6.7          2.5           5.8          1.8   virginica
102           7.1          3.0           5.9          2.1   virginica
143           6.8          3.2           5.9          2.3   virginica
100           6.3          3.3           6.0          2.5   virginica
125           7.2          3.2           6.0          1.8   virginica
109           7.2          3.6           6.1          2.5   virginica
135           7.7          3.0           6.1          2.3   virginica
130           7.4          2.8           6.1          1.9   virginica
107           7.3          2.9           6.3          1.8   virginica
131           7.9          3.8           6.4          2.0   virginica
105           7.6          3.0           6.6          2.1   virginica
117           7.7          3.8           6.7          2.2   virginica
122           7.7          2.8           6.7          2.0   virginica
118           7.7          2.6           6.9          2.3   virginica

In [36]:
# 'species'에 따라 데이터를 그룹화하세요
grouped_iris = iris.groupby('species')
grouped_iris.describe()

           sepal_length                                               \
                  count      mean       std  min  25%  50%  75%  max
species
setosa             50.0  5.006000  0.352490  4.3  4.8  5.0  5.2  5.8
versicolor         50.0  5.936000  0.516171  4.9  5.6  5.9  6.3  7.0
virginica          49.0  6.604082  0.632113  4.9  6.3  6.5  6.9  7.9

           sepal_width            ... petal_length      petal_width            \
                 count      mean  ...          75%  max       count      mean
species                           ...
setosa            50.0  3.428000  ...        1.575  1.9        50.0  0.246000
versicolor        50.0  2.770000  ...        4.600  5.1        50.0  1.326000
virginica         49.0  2.979592  ...        5.900  6.9        49.0  2.028571


                 std  min  25%  50%  75%  max
species
setosa      0.105386  0.1  0.2  0.2  0.3  0.6
versicolor  0.197753  1.0  1.2  1.3  1.5  1.8
virginica   0.276887  1.4  1.8  2.0  2.3  2.5

[3 rows x 32 columns]

In [37]:
# 그룹화한 데이터에서 'sepal_length'의 평균을 계산하세요
grouped_iris['sepal_length'].mean()

species
setosa        5.006000
versicolor    5.936000
virginica     6.604082
Name: sepal_length, dtype: float64

In [38]:
# 'petal_length'를 기준으로 데이터를 오름차순으로 정렬하세요.
iris.sort_values(by='petal_length', ascending=True)

     sepal_length  sepal_width  petal_length  petal_width    species
22            4.6          3.6           1.0          0.2     setosa
13            4.3          3.0           1.1          0.1     setosa
14            5.8          4.0           1.2          0.2     setosa
35            5.0          3.2           1.2          0.2     setosa
16            5.4          3.9           1.3          0.4     setosa
..            ...          ...           ...          ...        ...
131           7.9          3.8           6.4          2.0  virginica
105           7.6          3.0           6.6          2.1  virginica
117           7.7          3.8           6.7          2.2  virginica
122           7.7          2.8           6.7          2.0  virginica
118           7.7          2.6           6.9          2.3  virginica

[149 rows x 5 columns]

In [39]:
# 'petal_width'를 기준으로 데이터를 내림차순으로 정렬하세요
iris.sort_values(by='petal_width', ascending=False)

     sepal_length  sepal_width  petal_length  petal_width    species
109           7.2          3.6           6.1          2.5  virginica
144           6.7          3.3           5.7          2.5  virginica
100           6.3          3.3           6.0          2.5  virginica
114           5.8          2.8           5.1          2.4  virginica
140           6.7          3.1           5.6          2.4  virginica
..            ...          ...           ...          ...        ...
9             4.9          3.1           1.5          0.1     setosa
13            4.3          3.0           1.1          0.1     setosa
12            4.8          3.0           1.4          0.1     setosa
32            5.2          4.1           1.5          0.1     setosa
37            4.9          3.6           1.4          0.1     setosa

[149 rows x 5 columns]

In [40]:
# 'species'의 빈도수를 구하세요
iris['species'].value_counts()

species
setosa        50
versicolor    50
virginica     49
Name: count, dtype: int64

In [44]:
# 'species'값 중 'setosa'를 포함하는 행만 선택하세요.
iris[iris['species'].str.contains('setosa')]

    sepal_length  sepal_width  petal_length  petal_width species
0            5.1          3.5           1.4          0.2  setosa
1            4.9          3.0           1.4          0.2  setosa
2            4.7          3.2           1.3          0.2  setosa
3            4.6          3.1           1.5          0.2  setosa
4            5.0          3.6           1.4          0.2  setosa
5            5.4          3.9           1.7          0.4  setosa
6            4.6          3.4           1.4          0.3  setosa
7            5.0          3.4           1.5          0.2  setosa
8            4.4          2.9           1.4          0.2  setosa
9            4.9          3.1           1.5          0.1  setosa
10           5.4          3.7           1.5          0.2  setosa
11           4.8          3.4           1.6          0.2  setosa
12           4.8          3.0           1.4          0.1  setosa
13           4.3          3.0           1.1          0.1  setosa
14           5.8          4.0           1.2          0.2  setosa
15           5.7          4.4           1.5          0.4  setosa
16           5.4          3.9           1.3          0.4  setosa
17           5.1          3.5           1.4          0.3  setosa
18           5.7          3.8           1.7          0.3  setosa
19           5.1          3.8           1.5          0.3  setosa
20           5.4          3.4           1.7          0.2  setosa
21           5.1          3.7           1.5          0.4  setosa
22           4.6          3.6           1.0          0.2  setosa
23           5.1          3.3           1.7          0.5  setosa
24           4.8          3.4           1.9          0.2  setosa
25           5.0          3.0           1.6          0.2  setosa
26           5.0          3.4           1.6          0.4  setosa
27           5.2          3.5           1.5          0.2  setosa
28           5.2          3.4           1.4          0.2  setosa
29           4.7          3.2           1.6          0.2  setosa
30           4.8          3.1           1.6          0.2  setosa
31           5.4          3.4           1.5          0.4  setosa
32           5.2          4.1           1.5          0.1  setosa
33           5.5          4.2           1.4          0.2  setosa
34           4.9          3.1           1.5          0.2  setosa
35           5.0          3.2           1.2          0.2  setosa
36           5.5          3.5           1.3          0.2  setosa
37           4.9          3.6           1.4          0.1  setosa
38           4.4          3.0           1.3          0.2  setosa
39           5.1          3.4           1.5          0.2  setosa
40           5.0          3.5           1.3          0.3  setosa
41           4.5          2.3           1.3          0.3  setosa
42           4.4          3.2           1.3          0.2  setosa
43           5.0          3.5           1.6          0.6  setosa
44           5.1          3.8           1.9          0.4  setosa
45           4.8          3.0           1.4          0.3  setosa
46           5.1          3.8           1.6          0.2  setosa
47           4.6          3.2           1.4          0.2  setosa
48           5.3          3.7           1.5          0.2  setosa
49           5.0          3.3           1.4          0.2  setosa

In [43]:
# 'species'값 중 'setosa'로 시작하는 행을 선택하세요
iris[iris['species'].str.startswith('setosa')]

    sepal_length  sepal_width  petal_length  petal_width species
0            5.1          3.5           1.4          0.2  setosa
1            4.9          3.0           1.4          0.2  setosa
2            4.7          3.2           1.3          0.2  setosa
3            4.6          3.1           1.5          0.2  setosa
4            5.0          3.6           1.4          0.2  setosa
5            5.4          3.9           1.7          0.4  setosa
6            4.6          3.4           1.4          0.3  setosa
7            5.0          3.4           1.5          0.2  setosa
8            4.4          2.9           1.4          0.2  setosa
9            4.9          3.1           1.5          0.1  setosa
10           5.4          3.7           1.5          0.2  setosa
11           4.8          3.4           1.6          0.2  setosa
12           4.8          3.0           1.4          0.1  setosa
13           4.3          3.0           1.1          0.1  setosa
14           5.8          4.0           1.2          0.2  setosa
15           5.7          4.4           1.5          0.4  setosa
16           5.4          3.9           1.3          0.4  setosa
17           5.1          3.5           1.4          0.3  setosa
18           5.7          3.8           1.7          0.3  setosa
19           5.1          3.8           1.5          0.3  setosa
20           5.4          3.4           1.7          0.2  setosa
21           5.1          3.7           1.5          0.4  setosa
22           4.6          3.6           1.0          0.2  setosa
23           5.1          3.3           1.7          0.5  setosa
24           4.8          3.4           1.9          0.2  setosa
25           5.0          3.0           1.6          0.2  setosa
26           5.0          3.4           1.6          0.4  setosa
27           5.2          3.5           1.5          0.2  setosa
28           5.2          3.4           1.4          0.2  setosa
29           4.7          3.2           1.6          0.2  setosa
30           4.8          3.1           1.6          0.2  setosa
31           5.4          3.4           1.5          0.4  setosa
32           5.2          4.1           1.5          0.1  setosa
33           5.5          4.2           1.4          0.2  setosa
34           4.9          3.1           1.5          0.2  setosa
35           5.0          3.2           1.2          0.2  setosa
36           5.5          3.5           1.3          0.2  setosa
37           4.9          3.6           1.4          0.1  setosa
38           4.4          3.0           1.3          0.2  setosa
39           5.1          3.4           1.5          0.2  setosa
40           5.0          3.5           1.3          0.3  setosa
41           4.5          2.3           1.3          0.3  setosa
42           4.4          3.2           1.3          0.2  setosa
43           5.0          3.5           1.6          0.6  setosa
44           5.1          3.8           1.9          0.4  setosa
45           4.8          3.0           1.4          0.3  setosa
46           5.1          3.8           1.6          0.2  setosa
47           4.6          3.2           1.4          0.2  setosa
48           5.3          3.7           1.5          0.2  setosa
49           5.0          3.3           1.4          0.2  setosa

In [46]:
# 'species'값이 'virginica'로 끝나는 행을 선택하세요.
iris[iris['species'].str.endswith('virginica')]

     sepal_length  sepal_width  petal_length  petal_width    species
100           6.3          3.3           6.0          2.5  virginica
101           5.8          2.7           5.1          1.9  virginica
102           7.1          3.0           5.9          2.1  virginica
103           6.3          2.9           5.6          1.8  virginica
104           6.5          3.0           5.8          2.2  virginica
105           7.6          3.0           6.6          2.1  virginica
106           4.9          2.5           4.5          1.7  virginica
107           7.3          2.9           6.3          1.8  virginica
108           6.7          2.5           5.8          1.8  virginica
109           7.2          3.6           6.1          2.5  virginica
110           6.5          3.2           5.1          2.0  virginica
111           6.4          2.7           5.3          1.9  virginica
112           6.8          3.0           5.5          2.1  virginica
113           5.7          2.5           5.0          2.0  virginica
114           5.8          2.8           5.1          2.4  virginica
115           6.4          3.2           5.3          2.3  virginica
116           6.5          3.0           5.5          1.8  virginica
117           7.7          3.8           6.7          2.2  virginica
118           7.7          2.6           6.9          2.3  virginica
119           6.0          2.2           5.0          1.5  virginica
120           6.9          3.2           5.7          2.3  virginica
121           5.6          2.8           4.9          2.0  virginica
122           7.7          2.8           6.7          2.0  virginica
123           6.3          2.7           4.9          1.8  virginica
124           6.7          3.3           5.7          2.1  virginica
125           7.2          3.2           6.0          1.8  virginica
126           6.2          2.8           4.8          1.8  virginica
127           6.1          3.0           4.9          1.8  virginica
128           6.4          2.8           5.6          2.1  virginica
129           7.2          3.0           5.8          1.6  virginica
130           7.4          2.8           6.1          1.9  virginica
131           7.9          3.8           6.4          2.0  virginica
132           6.4          2.8           5.6          2.2  virginica
133           6.3          2.8           5.1          1.5  virginica
134           6.1          2.6           5.6          1.4  virginica
135           7.7          3.0           6.1          2.3  virginica
136           6.3          3.4           5.6          2.4  virginica
137           6.4          3.1           5.5          1.8  virginica
138           6.0          3.0           4.8          1.8  virginica
139           6.9          3.1           5.4          2.1  virginica
140           6.7          3.1           5.6          2.4  virginica
141           6.9          3.1           5.1          2.3  virginica
143           6.8          3.2           5.9          2.3  virginica
144           6.7          3.3           5.7          2.5  virginica
145           6.7          3.0           5.2          2.3  virginica
146           6.3          2.5           5.0          1.9  virginica
147           6.5          3.0           5.2          2.0  virginica
148           6.2          3.4           5.4          2.3  virginica
149           5.9          3.0           5.1          1.8  virginica

In [47]:
# 'species'의 'senosa'를 'SETOSA'로 대체하세요
iris['species'] = iris['species'].str.replace('setosa', 'SETOSA')
iris

     sepal_length  sepal_width  petal_length  petal_width    species
0             5.1          3.5           1.4          0.2     SETOSA
1             4.9          3.0           1.4          0.2     SETOSA
2             4.7          3.2           1.3          0.2     SETOSA
3             4.6          3.1           1.5          0.2     SETOSA
4             5.0          3.6           1.4          0.2     SETOSA
..            ...          ...           ...          ...        ...
145           6.7          3.0           5.2          2.3  virginica
146           6.3          2.5           5.0          1.9  virginica
147           6.5          3.0           5.2          2.0  virginica
148           6.2          3.4           5.4          2.3  virginica
149           5.9          3.0           5.1          1.8  virginica

[149 rows x 5 columns]

In [48]:
# iris 데이터셋에서 'species'열을 제거하세요.
iris.drop('species', axis=1, inplace=True)
iris

     sepal_length  sepal_width  petal_length  petal_width
0             5.1          3.5           1.4          0.2
1             4.9          3.0           1.4          0.2
2             4.7          3.2           1.3          0.2
3             4.6          3.1           1.5          0.2
4             5.0          3.6           1.4          0.2
..            ...          ...           ...          ...
145           6.7          3.0           5.2          2.3
146           6.3          2.5           5.0          1.9
147           6.5          3.0           5.2          2.0
148           6.2          3.4           5.4          2.3
149           5.9          3.0           5.1          1.8

[149 rows x 4 columns]